let upscDatabase = [];

// This function pulls the live data generated by your Python scraper
async function loadData() {
    try {
        const response = await fetch('data.json');
        if (!response.ok) throw new Error('Could not fetch data.json');
        upscDatabase = await response.json();
        renderDashboard();
    } catch (error) {
        console.error("Error loading data:", error);
    }
}

// Unified UI Dashboard Render Function
function renderDashboard() {
    const grid = document.querySelector('.articles-grid');
    if (!grid) return;
    grid.innerHTML = '';

    const chosenMonth = document.getElementById('month-selector').value;
    const activeLi = document.querySelector('.pillar-list li.active');
    const chosenPillar = activeLi ? activeLi.getAttribute('data-pillar') : 'all';

    let filteredList = upscDatabase.filter(item => {
        const matchesMonth = (chosenMonth === "all-months" || item.month === chosenMonth);
        const matchesPillar = (chosenPillar === "all" || item.pillar === chosenPillar);
        return matchesMonth && matchesPillar;
    });

    if (filteredList.length === 0) {
        grid.innerHTML = `<div style="grid-column: 1/-1; text-align: center; padding: 3rem;">No articles found.</div>`;
        return;
    }

    filteredList.forEach(article => {
        const card = document.createElement('div');
        card.className = 'card';
        card.innerHTML = `
            <div class="card-header">
                <span class="source-tag">${article.source}</span>
                <span class="time-tag">${article.time}</span>
            </div>
            <h3>${article.title}</h3>
            <p>${article.summary}</p>
            <button class="open-article-btn">Read Full Analysis</button>
        `;
        card.querySelector('.open-article-btn').addEventListener('click', () => openInAppReader(article));
        grid.appendChild(card);
    });
}

function openInAppReader(article) {
    document.getElementById('reader-modal-body').innerHTML = `
        <h1>${article.title}</h1>
        <p><strong>Source:</strong> ${article.source}</p>
        <div>${article.fullAnalysis.replace(/\\n/g, '<br><br>')}</div>
        <div style="margin-top:20px; padding:10px; background:#f0f0f0;">
            <h3>Prelims Facts</h3>
            <p>${article.prelimsSummary.replace(/\\n/g, '<br>')}</p>
        </div>
    `;
    document.getElementById('article-reader-overlay').style.display = 'flex';
}

// Initialize
loadData();
